// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VirtualEventTicketing.Data;

#nullable disable

namespace VirtualEventTicketing.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VirtualEventTicketing.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Online seminars and training",
                            Name = "Webinar"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Virtual music concerts",
                            Name = "Concert"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Interactive workshops",
                            Name = "Workshop"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Professional conferences",
                            Name = "Conference"
                        });
                });

            modelBuilder.Entity("VirtualEventTicketing.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableTickets = 100,
                            CategoryId = 1,
                            EventDateTime = new DateTime(2025, 10, 23, 14, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 49.99m,
                            Title = "Advanced C# Programming"
                        },
                        new
                        {
                            Id = 2,
                            AvailableTickets = 3,
                            CategoryId = 2,
                            EventDateTime = new DateTime(2025, 10, 30, 19, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 29.99m,
                            Title = "Virtual Jazz Night"
                        },
                        new
                        {
                            Id = 3,
                            AvailableTickets = 50,
                            CategoryId = 3,
                            EventDateTime = new DateTime(2025, 10, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 39.99m,
                            Title = "Web Development Workshop"
                        },
                        new
                        {
                            Id = 4,
                            AvailableTickets = 0,
                            CategoryId = 4,
                            EventDateTime = new DateTime(2025, 11, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 99.99m,
                            Title = "Tech Summit 2025"
                        });
                });

            modelBuilder.Entity("VirtualEventTicketing.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("VirtualEventTicketing.Models.PurchaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerTicket")
                        .HasColumnType("numeric");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("VirtualEventTicketing.Models.Event", b =>
                {
                    b.HasOne("VirtualEventTicketing.Models.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VirtualEventTicketing.Models.PurchaseItem", b =>
                {
                    b.HasOne("VirtualEventTicketing.Models.Event", "Event")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualEventTicketing.Models.Purchase", "Purchase")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("VirtualEventTicketing.Models.Category", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("VirtualEventTicketing.Models.Event", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("VirtualEventTicketing.Models.Purchase", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
